export const PERMISSIONS = {
  CAN_VIEW_DASHBOARD: "CAN_VIEW_DASHBOARD",
  CAN_MANAGE_USERS: "CAN_MANAGE_USERS",
  CAN_MANAGE_SUPERADMINS: "CAN_MANAGE_SUPERADMINS",
  CAN_UPDATE_USERS: "CAN_UPDATE_USERS",
  CAN_MANAGE_BOARDS: "CAN_MANAGE_BOARDS",
  CAN_MANAGE_SHIFTS: "CAN_MANAGE_SHIFTS",
  CAN_MANAGE_SUBJECTS: "CAN_MANAGE_SUBJECTS",
  CAN_REVIEW_QUESTIONS: "CAN_REVIEW_QUESTIONS",
  CAN_MANAGE_REVIEWER_PERMISSIONS: "CAN_MANAGE_REVIEWER_PERMISSIONS",
  CAN_EDIT_QUESTIONS: "CAN_EDIT_QUESTIONS",
  CAN_MANAGE_WRITER_PERMISSIONS: "CAN_MANAGE_WRITER_PERMISSIONS",
};
