export const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  REVIEWER: 'REVIEWER',
  CONTENT_WRITER: 'CONTENT_WRITER',
  USER: 'USER',
};

export const ROLE_PERMISSIONS = {
  SUPERADMIN: [
    'CAN_MANAGE_SUPERADMINS',
    'CAN_VIEW_DASHBOARD',
    'CAN_MANAGE_USERS',
    'CAN_UPDATE_USERS',
    'CAN_MANAGE_BOARDS',
    'CAN_MANAGE_SHIFTS',
    'CAN_MANAGE_SUBJECTS',
    'CAN_MANAGE_REVIEWER_PERMISSIONS',
    'CAN_MANAGE_WRITER_PERMISSIONS',
  ],
  ADMIN: [
    'CAN_VIEW_DASHBOARD',
    'CAN_MANAGE_USERS',
    'CAN_MANAGE_BOARDS',
    'CAN_MANAGE_SHIFTS',
    'CAN_MANAGE_SUBJECTS',
    'CAN_MANAGE_REVIEWER_PERMISSIONS',
    'CAN_MANAGE_WRITER_PERMISSIONS',
  ],
  REVIEWER: [
    'CAN_VIEW_DASHBOARD',
    'CAN_REVIEW_QUESTIONS',
  ],
  CONTENT_WRITER: [
    'CAN_VIEW_DASHBOARD',
    'CAN_EDIT_QUESTIONS',
  ],
  USER: [],
};